version: "3.9"
services:
  backend:
    build: ./backend
    container_name: cms_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

  frontend:
    build: ./frontend
    container_name: cms_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000
    command: sh -c "npm install && npm run dev -- --host"

  db:
    image: postgres:15
    container_name: cms_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cmsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
